# Config TestData
TestData_001:
  Method: GET
  Path: /api/users
  QueryString:
    page: "2"
  Ecode: "200"

TestData_002:
  Method: GET
  Path: /api/users/2
  Ecode: "200"

TestData_003:
  Method: POST
  Path: /api/register
  Ecode: "200"

TestData_004:
  Method: POST
  Path: /api/login
  Ecode: "200"