# Run Required 
run_Site: SIT       
run_Domain: TrafficManager      

# Config Domain
Domain:
  SIT:
    SG_ASSE: http://10.84.13.71
    HK_ASEA: http://10.84.145.12
    TrafficManager: https://reqres.in
  PRD:
    SG_ASSE: http://10.84.13.712
    HK_ASEA: http://10.84.145.123
    TrafficManager: https://reqres.prd.in

# Config Path
TestCase_001:
  Method: GET
  Path: /api/users
  QueryString:
    page: "2"
  Ecode: "200"

TestCase_002:
  Method: GET
  Path: /api/users/2
  Ecode: "200"

TestCase_003:
  Method: POST
  Path: /api/register
  Ecode: "200"

TestCase_004:
  Method: POST
  Path: /api/login
  Ecode: "200"